# Generated by Django 4.2.1 on 2023-06-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyect',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='proyect',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='image',
            field=models.ImageField(upload_to='proyects'),
        ),
    ]
